all: nds32le-linux-glibc-v3_pre_compiled.tar.gz
	tar xfvz nds32le-linux-glibc-v3_pre_compiled.tar.gz

nds32le-linux-glibc-v3_pre_compiled.tar.gz:
	curl "https://drive.usercontent.google.com/download?id=1K2HsLl70LIVj6i7GJ97Bfi2c1FLPf2E6&confirm=xxx" -o nds32le-linux-glibc-v3_pre_compiled.tar.gz

