all: nds32le-linux-glibc-v3_pre_compiled.tar.gz
	tar xfvz nds32le-linux-glibc-v3_pre_compiled.tar.gz

nds32le-linux-glibc-v3_pre_compiled.tar.gz:
	wget --no-check-certificate ""https://1drv.ms/u/s!AiBN7sgxZdsXhkJ8-k84H3FR8hY9?e=OUkvS4 -O nds32le-linux-glibc-v3_pre_compiled.tar.gz

