NEXMON_CHIP=CHIP_VER_MTK
NEXMON_CHIP_NUM=`$(NEXMON_ROOT)/buildtools/scripts/getdefine.sh $(NEXMON_CHIP)`
NEXMON_FW_VERSION=FW_VER_MTK
NEXMON_FW_VERSION_NUM=`$(NEXMON_ROOT)/buildtools/scripts/getdefine.sh $(NEXMON_FW_VERSION)`

NEXMON_ARCH=nds32

HEADER_SIZE=0x30

1ST_SEGMENT_START=0x0
1ST_SEGMENT_SIZE=0x0

2ND_SEGMENT_START=0x0
2ND_SEGMENT_SIZE=0x0

SWAP_IMG_START=0x0
SWAP_IMG_SIZE=0x0

RAM_FILE=WIFI_RAM_CODE_soc1_0_1a_1.bin
RAMSTART=0xF0177000
RAMSIZE=471072

NEX_LITPOOL_START=0x0
NEX_LITPOOL_SIZE=0x0

PATCHSTART=0x0
PATCHSIZE=0x0
